### ISSUE TITLE
Env variable highlighting

### ISSUE THREAD

**Issue by Fuco1** [preetpalS/emacs-dotenv-mode#2]
I wrote a blog post about this some time ago https://fuco1.github.io/2017-06-11-Font-locking-with-custom-matchers.html I think you could pretty much lift the code from there and copy/paste it in to have it working.

**Comment by preetpalS** [comment]
Thanks for the suggestion and contribution, I took the code and was able to incorporate it into the mode some very minor changes (I had to add `\$` to the mode's syntax table and  I also added support for command substitution syntax like `"sample $(substituted command)"`).

You can see the changes I made [here](https://github.com/preetpalS/emacs-dotenv-mode/blob/6a8aebfb7cba558a9ca63f43db40db7ed0b5436d/dotenv-mode.el#L51). I added a reference to your blog and and mentioned your contribution in the comments for the code I adapted from your blog.

**Comment by Fuco1** [comment]
Thanks, awesome! I deal with a lot of docker deployments right now, loving this mode!

**Comment by Fuco1** [comment]
By the way, I use the macro `-when-let` from dash which you probably have installed because of other packages, but you should then either declare the dependency or replace it with (let ((x ...)) (when x ...))).  This might potentially break for someone who doesn't have dash installed now.


```
(-when-let (string-syntax (nth 3 (syntax-ppss)))
  (when (= string-syntax 34)
    (throw 'done (point))))
```

expands to 

```
(let ((string-syntax (nth 3 (syntax-ppss))))
  (when (and string-syntax (= string-syntax 34))
    (throw 'done (point))))
```

**Comment by preetpalS** [comment]
Good catch! I have had *dash* installed for so long, I didn't realize that it's not included by default in Emacs. I chose to replace the usage of `-when-let` with the expansion for the following reasons:
- It avoids having to change the installation instructions (for those not installing it via MELPA).
- It avoids having to deal with dependency management which makes the library simpler IMO.

I'm glad that you're enjoying the mode by the way. I decided to write it since I found also found myself working with *.env* files in some of my own projects (mainly Rails apps but also a single Golang web app). Your contribution was really useful, I also ended up improving the syntax highlighting (there is no longer any highlighting of the `:` and `=` symbols; I didn't know how to avoid this before) in other ways after investigating how your code worked.

On a side note, there's a pretty good chance that everyone installing this package has [dash](https://github.com/magnars/dash.el) installed either directly or via another package as a dependency. I wonder if anyone with this package installed would actually ever have encountered any issues from not having dash installed.

**Comment by preetpalS** [comment]
Also thanks for [smartparens](https://github.com/Fuco1/smartparens). I've been using it for ages now, so it feels nice to have created something that you find useful as well (albeit not as awesome).

**Comment by Fuco1** [comment]
Oh thanks :)

Yea, dash comes with magit, flycheck and smartparens which are some of the most used packages according to melpa stats, but there are still some people who don't use it.

Actually in emacs 25 there is a built-in macro `when-let`, it has a byt different syntax but can be used too.  But that requires at least version 25 I think.  I agree there is no point in having dash as a dependency for just that one use.
